### ISSUE TITLE
An error "Pat shouldnot happen"

### ISSUE THREAD

**Issue by pirapira** [QuickChick/Luck#3] opened 2017-01-30 20:53 UTC
Sometimes [the error](https://github.com/QuickChick/Luck/blob/c64d06ee4e7846eed1625dda12f2e67cdf8cab9d/luck/src/Core/Semantics.hs#L429) `Pat shouldnothappen` happens.

[The luck file](https://github.com/pirapira/minus-minus-solidity/blob/shouldnot/luck_generator/minus-minus-solidity.luck).

```
$ git clone git@github.com:pirapira/minus-minus-solidity.git
$ mkdir minus-minus-solidity
$ git checkout shouldnot
$ stack build && stack exec mms-exe
mms-exe: Pat shouldnot happen
CallStack (from HasCallStack):
  error, called at src/Core/Semantics.hs:429:26 in luck-0.1.0.0-LJij1R78ObT1aQOfaHb3dW:Core.Semantics
```

This error happens with 70% probability.

**Comment by lemonidas** [comment] 2017-01-30 23:32
This was caused by an obscure optimization firing unexpectedly which invalidated some invariants. Fixed now (updated invariants).

**Closed as completed by lemonidas** 2017-01-30 23:32 UTC

**Comment by pirapira** [comment] 2017-01-30 23:35
Thanks!
